window.ZM_TRACKS = [
  {
    title: "Ömrüm",
    artist: "Eypio",
    duration: "2:38",
    durationSeconds: 158.128,
    src: "file:///C:/Users/ziyam/Desktop/%C3%96mrum%20%20%20Eypio.m4a",
    portableSrc: "assets/music/01-omrum-eypio.m4a",
    source: "https://www.youtube.com/watch?v=Zrw-4bMBwAA",
    favoriteAt: 132.44,
    favoriteLine: "Ömrüm, ömrüm, ömrüm",
    favoriteNote: "Qısa bir sözün içinə uzun bir həyat sığır.",
    meaningTitle: "Keçmişin ağırlığı, yolun davamı.",
    meaning: "Bu mahnı insanın daşıdığı yükü, keçmişi silmək istəyini və bütün yorğunluğa baxmayaraq yoluna davam etməsini danışır.",
    lyrics: [
      { time: 5.28, text: "Öyle bir ağırlık var benim hep üstümde" },
      { time: 10.0, text: "Onlara ben küstüm de" },
      { time: 13.04, text: "Hatam var her özrümde" },
      { time: 15.35, text: "Günahım var da ben ondan korkmam" },
      { time: 17.55, text: "Tutmadım mı söyle ben seni el üstünde" },
      { time: 22.36, text: "Onlara bu suçlu de" },
      { time: 25.52, text: "Yalanmış her sözünde" },
      { time: 27.45, text: "Haberim var da her bir durumdan" },
      { time: 29.1, text: "Ya vur beni ya da" },
      { time: 31.15, text: "Bu yükü al üstümden" },
      { time: 34.88, text: "Ateşim, külüm de sen" },
      { time: 37.88, text: "Dikensin, gülüm desem" },
      { time: 39.72, text: "Gitmez ki burda her şey yolunda" },
      { time: 42.18, text: "Çözülür işler de, basit bi' kulum desen" },
      { time: 47.2, text: "Çektiğim her zulümde sen" },
      { time: 50.4, text: "Bi' kere gülümsesen" },
      { time: 52.2, text: "O zaman demek ki işler yolunda" },
      { time: 80.08, text: "Çizerim üstünü sonra da hatırlamam" },
      { time: 84.68, text: "Demek ki geçmiş zaman" },
      { time: 87.8, text: "Haber yok yeraltından" },
      { time: 92.52, text: "Bu kurda, ormanda inan ki her yer kapan" },
      { time: 97.08, text: "Çok gördüm yoldan sapan" },
      { time: 100.2, text: "Çıkış yok yeraltından" },
      { time: 105.04, text: "Ya vur beni ya da" },
      { time: 107.15, text: "Bu yükü al üstümden" },
      { time: 109.72, text: "Ateşim, külüm de sen" },
      { time: 112.68, text: "Dikensin, gülüm desem" },
      { time: 114.2, text: "Gitmez ki burda her şey yolunda" },
      { time: 117.56, text: "Çözülür işler de, basit bi' kulum desen" },
      { time: 122.04, text: "Çektiğim her zulümde sen" },
      { time: 125.2, text: "Bi' kere gülümsesen" },
      { time: 126.56, text: "O zaman demek ki işler yolunda" },
      { time: 132.44, text: "Ömrüm, ömrüm, ömrüm" },
      { time: 138.68, text: "Yalan dünyada neler gördüm" },
      { time: 144.92, text: "Ömrüm, ömrüm, ömrüm" },
      { time: 151.32, text: "Bu aşkta ben Veysel gibi kördüm" }
    ]
  },
  {
    title: "Xəzərəm",
    artist: "Miri Yusif",
    duration: "3:39",
    durationSeconds: 218.854,
    src: "file:///C:/Users/ziyam/Desktop/AUD-20251117-WA0316.mp3",
    portableSrc: "assets/music/02-aud-20251117.mp3",
    source: "https://www.youtube.com/watch?v=4u8HwHAD3vA",
    favoriteAt: 44.06,
    favoriteLine: "Mən Bakını qucaqlaya bilməyən Xəzərəm",
    favoriteNote: "Darıxmağı Bakı və Xəzər qədər böyük deyən misra.",
    meaningTitle: "Qucaqlaya bilmədiyin qədər böyük həsrət.",
    meaning: "Mahnı uzaqlığı, ayrılığı və bir insanı bütün şəhərə bənzədəcək qədər güclü darıxmağı danışır.",
    lyrics: [
      { time: 16.8, text: "Hicran qanadlandı" },
      { time: 20.72, text: "Havada süzdü məni" },
      { time: 23.87, text: "Sənsizlik bərbaddır" },
      { time: 27.99, text: "Yaman üzdü məni" },
      { time: 32.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 35.9, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 39.96, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 44.06, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 48.0, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 51.9, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 55.88, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 59.92, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 64.04, text: "Sıxılaram, qaldıra bilmərəm yükü" },
      { time: 67.58, text: "Arxamca saralar sənə baxan gözüm kökü" },
      { time: 71.58, text: "Bu son aralar sənə gələn yollar bürkü" },
      { time: 75.72, text: "Ağlar mahnılar hönkür-hönkür" },
      { time: 78.35, text: "Və sən gedəndən..." },
      { time: 80.78, text: "Hicran qanadlandı" },
      { time: 84.36, text: "Havada süzdü məni" },
      { time: 86.52, text: "Sənsizlik bərbaddır" },
      { time: 93.56, text: "Yaman üzdü məni" },
      { time: 96.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 100.16, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 104.04, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 108.04, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 111.7, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 116.14, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 119.8, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 123.92, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 127.94, text: "Zamanı mənə qaytar" },
      { time: 131.54, text: "Peşman olmaq verməz fayda" },
      { time: 136.06, text: "Sənsiz keçən günlər, aylar" },
      { time: 140.14, text: "Yadımdadır, səsin mənə laylay" },
      { time: 144.26, text: "Hicran qanadlandı" },
      { time: 147.76, text: "Havada süzdü məni" },
      { time: 151.96, text: "Sənsizlik bərbaddır" },
      { time: 156.78, text: "Yaman üzdü məni" },
      { time: 160.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 163.96, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 167.98, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 171.98, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 176.08, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 180.22, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 184.0, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 188.02, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" }
    ]
  },
  {
    title: "Biliyorsun",
    artist: "Sezen Aksu",
    duration: "5:17",
    durationSeconds: 316.697,
    src: "file:///C:/Users/ziyam/Desktop/AUD-20250709-WA0314.m4a",
    portableSrc: "assets/music/03-aud-20250709.m4a",
    source: "https://www.youtube.com/watch?v=-aW8x1jTA2U",
    favoriteAt: 83.9,
    favoriteLine: "Beraber olamayız, benim gibi biliyorsun",
    favoriteNote: "İki insanın bildiyi, amma deyə bilmədiyi həqiqət.",
    meaningTitle: "Doğru insan, mümkün olmayan zaman.",
    meaning: "Bir-birini anlayan iki insanın ayrı dünyalara aid olduğunu qəbul etməsi və danışmadan belə anlaşa bilməsi haqqındadır.",
    lyrics: [
      { time: 29.98, text: "Hayat bazen öyle insafsız ki" },
      { time: 34.1, text: "Küçük bir boşluğundan yakalar" },
      { time: 39.5, text: "Hissettirmez en zayıf anında" },
      { time: 44.6, text: "Seni ta yüreğinden yaralar" },
      { time: 51.18, text: "Ellerin kolların bağlansa da" },
      { time: 57.12, text: "Başında kasırgalar kopsa da" },
      { time: 62.9, text: "Sen tüm gücünle karşı koysan da" },
      { time: 68.94, text: "Seni acımasız sevdaya salar" },
      { time: 76.7, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 83.9, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 89.78, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 96.04, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 103.82, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 110.26, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 115.86, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 121.6, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 156.8, text: "Haklısın, biraz geç karşılaştık" },
      { time: 161.72, text: "Oysa hiç konuşmadan anlaştık" },
      { time: 166.86, text: "Bazı şeyler var ki söylenmiyor" },
      { time: 172.64, text: "Biz seninle sözleri susarak aştık" },
      { time: 180.16, text: "İnsan acılarla kıvransa da" },
      { time: 185.72, text: "Ve o aşkta bir daha doğsa da" },
      { time: 192.4, text: "Dünyasını yeniden kursa da" },
      { time: 199.02, text: "Düşler ve gerçekler ayrı ayrı yaşar" },
      { time: 206.24, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 212.1, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 218.16, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 224.36, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 233.08, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 239.22, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 244.74, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 250.62, text: "Sen kendi dünyanın toprağında büyüyorsun" }
    ]
  },
  {
    title: "Kaş (Akustik)",
    artist: "Nuri Sərinləndirici & Jane",
    duration: "4:00",
    durationSeconds: 239.673,
    src: "file:///C:/Users/ziyam/Desktop/NuriSrinlndiriciJane-KaAkustik_@MusicSOBot.mp3",
    portableSrc: "assets/music/04-nuri-serinlendirici-jane-ka-akustik.mp3",
    source: "https://www.youtube.com/watch?v=0VXJWR_hDvQ",
    favoriteAt: 10.92,
    favoriteLine: "Məni anlayasan deyə",
    favoriteNote: "Bütün mahnının arzusu bu qısa cümlədədir.",
    meaningTitle: "Bir gün hiss etdiyini qarşı tərəf də anlasın.",
    meaning: "Darıxmağın, unuda bilməməyin və yaşananların qarşı tərəf tərəfindən nəhayət anlaşılması arzusudur.",
    lyrics: [
      { time: 0.52, text: "Kaş ürəyin ola daş" },
      { time: 3.72, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 7.12, text: "O gecə nəsə baş verər" },
      { time: 10.92, text: "Məni anlayasan deyə" },
      { time: 17.04, text: "Ürək elə eşq istər" },
      { time: 20.76, text: "O gələcəyi oxşasın" },
      { time: 24.8, text: "Ölən, dirilən hisslər" },
      { time: 28.64, text: "Yeni həyata başlasın" },
      { time: 32.1, text: "Sözlərimi ruhunla" },
      { time: 35.2, text: "Nə də qəlbinlə" },
      { time: 37.12, text: "Duya bilmədin" },
      { time: 40.28, text: "Gözlərimə baxdıqca" },
      { time: 44.0, text: "Nələr hiss etdim, guya bilmədin" },
      { time: 49.32, text: "Kaş ürəyin ola daş" },
      { time: 52.48, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 57.16, text: "O gecə nəsə baş verər" },
      { time: 59.76, text: "Məni anlayasan deyə" },
      { time: 64.85, text: "Kaş səni daha yavaş" },
      { time: 68.48, text: "Unudum, unudum" },
      { time: 70.65, text: "Cana düşər təlaş" },
      { time: 73.16, text: "O gecə nəsə baş verər" },
      { time: 75.32, text: "Məni anlayasan deyə" },
      { time: 112.48, text: "Ürək elə eşq istər" },
      { time: 115.94, text: "O gələcəyi oxşasın" },
      { time: 120.28, text: "Ölən, dirilən hisslər" },
      { time: 124.28, text: "Yeni həyata başlasın" },
      { time: 128.08, text: "Sözlərimi ruhunla" },
      { time: 130.76, text: "Nə də qəlbinlə" },
      { time: 132.72, text: "Duya bilmədin" },
      { time: 135.88, text: "Gözlərimə baxdıqca" },
      { time: 139.56, text: "Nələr hiss etdim, guya bilmədin" },
      { time: 144.88, text: "Kaş ürəyin ola daş" },
      { time: 148.08, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 152.62, text: "O gecə nəsə baş verər" },
      { time: 155.28, text: "Məni anlayasan deyə" },
      { time: 160.48, text: "Kaş səni daha yavaş" },
      { time: 164.04, text: "Unudum, unudum" },
      { time: 165.16, text: "Cana düşər təlaş" },
      { time: 168.32, text: "O gecə nəsə baş verər" },
      { time: 170.88, text: "Məni anlayasan deyə" },
      { time: 207.32, text: "Kaş ürəyin ola daş" },
      { time: 210.56, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 215.2, text: "O gecə nəsə baş verər" },
      { time: 217.72, text: "Məni anlayasan deyə" },
      { time: 222.92, text: "Kaş səni daha yavaş" },
      { time: 226.48, text: "Unudum, unudum" },
      { time: 228.3, text: "Cana düşər təlaş" },
      { time: 231.24, text: "O gecə nəsə baş verər" },
      { time: 233.36, text: "Məni anlayasan deyə" }
    ]
  },
  {
    title: "Yuxu",
    artist: "Nuri & Jane",
    duration: "3:33",
    durationSeconds: 213,
    src: "file:///C:/Users/ziyam/Desktop/1772547560467.mp3",
    portableSrc: "assets/music/05-1772547560467.mp3",
    source: "https://www.youtube.com/watch?v=KfvJ_ohsjjs",
    favoriteAt: 85.7,
    favoriteLine: "Ürək qədər yaxındasan",
    favoriteNote: "Məsafəni bir cümlə ilə yox edən hissə.",
    meaningTitle: "Uzaqda olsa da yuxuda və ürəkdə yaxın.",
    meaning: "Mahnı ayrılıqdan sonra belə bir insanın yuxuda, ruhda və gündəlik düşüncələrdə yanında qalmasını danışır.",
    lyrics: [
      { time: 31.86, text: "Küsdürməsin sözüm səni" },
      { time: 35.31, text: "Qədəh-qədəh süzüm səni" },
      { time: 39.12, text: "Unutmuşam özüm səni, yar" },
      { time: 45.88, text: "Mən indi öz yolumdayam" },
      { time: 49.28, text: "Ümidlərin yanındayam" },
      { time: 52.5, text: "Artıq yolun sonundayam, yar" },
      { time: 56.78, text: "Bu şəhərdə gələrikmi" },
      { time: 64.72, text: "Yenə üz-üzə?" },
      { time: 68.86, text: "Nə fərqi var uzaqdasan" },
      { time: 73.0, text: "Nə fərq edər yaxındasan" },
      { time: 76.36, text: "Hər gün şirin yuxumdasan" },
      { time: 79.56, text: "Yuxumdasan, yar" },
      { time: 83.84, text: "Ruhumdasan, yar" },
      { time: 85.7, text: "Elə bilmə uzaqdasan" },
      { time: 89.62, text: "Ürək qədər yaxındasan" },
      { time: 92.5, text: "Hər gün şirin röyamdasan" },
      { time: 96.3, text: "Canımdasan, yar" },
      { time: 99.66, text: "Yanımdasan, yar" },
      { time: 128.04, text: "Bu ayrılıq nədir ki sən" },
      { time: 131.3, text: "Gözündə çox böyütmüsən" },
      { time: 135.58, text: "Kimin sözün eşitmisən, yar?" },
      { time: 141.96, text: "Unutmağı unutmusan" },
      { time: 144.72, text: "Bu sevgini soyutmusan" },
      { time: 148.26, text: "Nə var geri qayıtmısan, yar?" },
      { time: 152.44, text: "Bu şəhərdə gələrikmi" },
      { time: 159.48, text: "Yenə üz-üzə?" },
      { time: 163.1, text: "Nə fərqi var uzaqdasan" },
      { time: 168.08, text: "Nə fərq edər yaxındasan" },
      { time: 170.8, text: "Hər gün şirin yuxumdasan" },
      { time: 174.22, text: "Yuxumdasan, yar" },
      { time: 178.4, text: "Ruhumdasan, yar" },
      { time: 180.42, text: "Elə bilmə uzaqdasan" },
      { time: 183.88, text: "Ürək qədər yaxındasan" },
      { time: 187.08, text: "Hər gün şirin röyamdasan" },
      { time: 190.32, text: "Canımdasan, yar" },
      { time: 194.62, text: "Yanımdasan, yar" }
    ]
  }
];
