window.ZM_TRACKS = [
  {
    title: "Ömrüm",
    artist: "Eypio",
    duration: "2:38",
    durationSeconds: 158.128,
    fileName: "Ömrum   Eypio.m4a",
    mood: "Gecə · düşüncə",
    accent: "#20a9b5",
    accentSoft: "#6a2b20",
    src: "file:///C:/Users/ziyam/Desktop/%C3%96mrum%20%20%20Eypio.m4a",
    portableSrc: "assets/music/01-omrum-eypio.m4a",
    favoriteAt: 132.44,
    favoriteLine: "Ömrüm, ömrüm, ömrüm",
    favoriteNote: "Qısa bir sözün içinə uzun bir həyat sığır.",
    meaningTitle: "Keçmişin ağırlığı, yolun davamı.",
    meaning:
      "Bu mahnı insanın daşıdığı yükü, keçmişi silmək istəyini və bütün yorğunluğa baxmayaraq yoluna davam etməsini danışır.",
    lyrics: [
      { time: 5.28, text: "Öyle bir ağırlık var benim hep üstümde" },
      { time: 10.0, text: "Onlara ben küstüm de" },
      { time: 13.04, text: "Hatam var her özrümde" },
      { time: 15.35, text: "Günahım var da ben ondan korkmam" },
      { time: 17.55, text: "Tutmadım mı söyle ben seni el üstünde" },
      { time: 22.36, text: "Onlara bu suçlu de" },
      { time: 25.52, text: "Yalanmış her sözünde" },
      { time: 27.45, text: "Haberim var da her bir durumdan" },
      { time: 29.1, text: "Ya vur beni ya da" },
      { time: 31.15, text: "Bu yükü al üstümden" },
      { time: 34.88, text: "Ateşim, külüm de sen" },
      { time: 37.88, text: "Dikensin, gülüm desem" },
      { time: 39.72, text: "Gitmez ki burda her şey yolunda" },
      { time: 42.18, text: "Çözülür işler de, basit bi' kulum desen" },
      { time: 47.2, text: "Çektiğim her zulümde sen" },
      { time: 50.4, text: "Bi' kere gülümsesen" },
      { time: 52.2, text: "O zaman demek ki işler yolunda" },
      { time: 80.08, text: "Çizerim üstünü sonra da hatırlamam" },
      { time: 84.68, text: "Demek ki geçmiş zaman" },
      { time: 87.8, text: "Haber yok yeraltından" },
      { time: 92.52, text: "Bu kurda, ormanda inan ki her yer kapan" },
      { time: 97.08, text: "Çok gördüm yoldan sapan" },
      { time: 100.2, text: "Çıkış yok yeraltından" },
      { time: 105.04, text: "Ya vur beni ya da" },
      { time: 107.15, text: "Bu yükü al üstümden" },
      { time: 109.72, text: "Ateşim, külüm de sen" },
      { time: 112.68, text: "Dikensin, gülüm desem" },
      { time: 114.2, text: "Gitmez ki burda her şey yolunda" },
      { time: 117.56, text: "Çözülür işler de, basit bi' kulum desen" },
      { time: 122.04, text: "Çektiğim her zulümde sen" },
      { time: 125.2, text: "Bi' kere gülümsesen" },
      { time: 126.56, text: "O zaman demek ki işler yolunda" },
      { time: 132.44, text: "Ömrüm, ömrüm, ömrüm" },
      { time: 138.68, text: "Yalan dünyada neler gördüm" },
      { time: 144.92, text: "Ömrüm, ömrüm, ömrüm" },
      { time: 151.32, text: "Bu aşkta ben Veysel gibi kördüm" },
    ],
  },
  {
    title: "Xəzərəm",
    artist: "Miri Yusif",
    duration: "3:39",
    durationSeconds: 218.854,
    fileName: "AUD-20251117-WA0316.mp3",
    mood: "Dəniz · həsrət",
    accent: "#39b8c4",
    accentSoft: "#173c64",
    src: "file:///C:/Users/ziyam/Desktop/AUD-20251117-WA0316.mp3",
    portableSrc: "assets/music/02-xezerem-miri-yusif.mp3",
    favoriteAt: 44.06,
    favoriteLine: "Mən Bakını qucaqlaya bilməyən Xəzərəm",
    favoriteNote: "Darıxmağı Bakı və Xəzər qədər böyük deyən misra.",
    meaningTitle: "Qucaqlaya bilmədiyin qədər böyük həsrət.",
    meaning:
      "Mahnı uzaqlığı, ayrılığı və bir insanı bütün şəhərə bənzədəcək qədər güclü darıxmağı danışır.",
    lyrics: [
      { time: 16.8, text: "Hicran qanadlandı" },
      { time: 20.72, text: "Havada süzdü məni" },
      { time: 23.87, text: "Sənsizlik bərbaddır" },
      { time: 27.99, text: "Yaman üzdü məni" },
      { time: 32.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 35.9, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 39.96, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 44.06, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 48.0, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 51.9, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 55.88, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 59.92, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 64.04, text: "Sıxılaram, qaldıra bilmərəm yükü" },
      { time: 67.58, text: "Arxamca saralar sənə baxan gözüm kökü" },
      { time: 71.58, text: "Bu son aralar sənə gələn yollar bürkü" },
      { time: 75.72, text: "Ağlar mahnılar hönkür-hönkür" },
      { time: 78.35, text: "Və sən gedəndən..." },
      { time: 80.78, text: "Hicran qanadlandı" },
      { time: 84.36, text: "Havada süzdü məni" },
      { time: 86.52, text: "Sənsizlik bərbaddır" },
      { time: 93.56, text: "Yaman üzdü məni" },
      { time: 96.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 100.16, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 104.04, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 108.04, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 111.7, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 116.14, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 119.8, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 123.92, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 127.94, text: "Zamanı mənə qaytar" },
      { time: 131.54, text: "Peşman olmaq verməz fayda" },
      { time: 136.06, text: "Sənsiz keçən günlər, aylar" },
      { time: 140.14, text: "Yadımdadır, səsin mənə laylay" },
      { time: 144.26, text: "Hicran qanadlandı" },
      { time: 147.76, text: "Havada süzdü məni" },
      { time: 151.96, text: "Sənsizlik bərbaddır" },
      { time: 156.78, text: "Yaman üzdü məni" },
      { time: 160.14, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 163.96, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 167.98, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 171.98, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
      { time: 176.08, text: "Əlimdə deyil əllərin, məsələn" },
      { time: 180.22, text: "Səni çox sevmişəm sənə nəzərən" },
      { time: 184.0, text: "Şəklini gah əzizlərəm, gah əzərəm" },
      { time: 188.02, text: "Mən Bakını qucaqlaya bilməyən Xəzərəm" },
    ],
  },
  {
    title: "Biliyorsun",
    artist: "Sezen Aksu",
    duration: "5:17",
    durationSeconds: 316.697,
    fileName: "AUD-20250709-WA0314.m4a",
    mood: "Sakitlik · ayrılıq",
    accent: "#d48b9a",
    accentSoft: "#563047",
    src: "file:///C:/Users/ziyam/Desktop/AUD-20250709-WA0314.m4a",
    portableSrc: "assets/music/03-biliyorsun-sezen-aksu.m4a",
    favoriteAt: 83.9,
    favoriteLine: "Beraber olamayız, benim gibi biliyorsun",
    favoriteNote: "İki insanın bildiyi, amma deyə bilmədiyi həqiqət.",
    meaningTitle: "Doğru insan, mümkün olmayan zaman.",
    meaning:
      "Bir-birini anlayan iki insanın ayrı dünyalara aid olduğunu qəbul etməsi və danışmadan belə anlaşa bilməsi haqqındadır.",
    lyrics: [
      { time: 29.98, text: "Hayat bazen öyle insafsız ki" },
      { time: 34.1, text: "Küçük bir boşluğundan yakalar" },
      { time: 39.5, text: "Hissettirmez en zayıf anında" },
      { time: 44.6, text: "Seni ta yüreğinden yaralar" },
      { time: 51.18, text: "Ellerin kolların bağlansa da" },
      { time: 57.12, text: "Başında kasırgalar kopsa da" },
      { time: 62.9, text: "Sen tüm gücünle karşı koysan da" },
      { time: 68.94, text: "Seni acımasız sevdaya salar" },
      { time: 76.7, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 83.9, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 89.78, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 96.04, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 103.82, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 110.26, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 115.86, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 121.6, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 156.8, text: "Haklısın, biraz geç karşılaştık" },
      { time: 161.72, text: "Oysa hiç konuşmadan anlaştık" },
      { time: 166.86, text: "Bazı şeyler var ki söylenmiyor" },
      { time: 172.64, text: "Biz seninle sözleri susarak aştık" },
      { time: 180.16, text: "İnsan acılarla kıvransa da" },
      { time: 185.72, text: "Ve o aşkta bir daha doğsa da" },
      { time: 192.4, text: "Dünyasını yeniden kursa da" },
      { time: 199.02, text: "Düşler ve gerçekler ayrı ayrı yaşar" },
      { time: 206.24, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 212.1, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 218.16, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 224.36, text: "Sen kendi dünyanın toprağında büyüyorsun" },
      { time: 233.08, text: "Sen de benim kadar gerçekleri görüyorsun" },
      { time: 239.22, text: "Beraber olamayız, benim gibi biliyorsun" },
      { time: 244.74, text: "Bir başka dünyanın insanısın yavrucağım" },
      { time: 250.62, text: "Sen kendi dünyanın toprağında büyüyorsun" },
    ],
  },
  {
    title: "Kaş (Akustik)",
    artist: "Nuri Sərinləndirici & Jane",
    duration: "4:00",
    durationSeconds: 239.673,
    fileName: "NuriSrinlndiriciJane-KaAkustik_@MusicSOBot.mp3",
    mood: "Akustik · darıxmaq",
    accent: "#d06d49",
    accentSoft: "#5d3022",
    src: "file:///C:/Users/ziyam/Desktop/NuriSrinlndiriciJane-KaAkustik_@MusicSOBot.mp3",
    portableSrc: "assets/music/04-kas-akustik.mp3",
    favoriteAt: 10.92,
    favoriteLine: "Məni anlayasan deyə",
    favoriteNote: "Bütün mahnının arzusu bu qısa cümlədədir.",
    meaningTitle: "Bir gün hiss etdiyini qarşı tərəf də anlasın.",
    meaning:
      "Darıxmağın, unuda bilməməyin və yaşananların qarşı tərəf tərəfindən nəhayət anlaşılması arzusudur.",
    lyrics: [
      { time: 0.52, text: "Kaş ürəyin ola daş" },
      { time: 3.72, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 7.12, text: "O gecə nəsə baş verər" },
      { time: 10.92, text: "Məni anlayasan deyə" },
      { time: 17.04, text: "Ürək elə eşq istər" },
      { time: 20.76, text: "O gələcəyi oxşasın" },
      { time: 24.8, text: "Ölən, dirilən hisslər" },
      { time: 28.64, text: "Yeni həyata başlasın" },
      { time: 32.1, text: "Sözlərimi ruhunla" },
      { time: 35.2, text: "Nə də qəlbinlə" },
      { time: 37.12, text: "Duya bilmədin" },
      { time: 40.28, text: "Gözlərimə baxdıqca" },
      { time: 44.0, text: "Nələr hiss etdim, guya bilmədin" },
      { time: 49.32, text: "Kaş ürəyin ola daş" },
      { time: 52.48, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 57.16, text: "O gecə nəsə baş verər" },
      { time: 59.76, text: "Məni anlayasan deyə" },
      { time: 64.85, text: "Kaş səni daha yavaş" },
      { time: 68.48, text: "Unudum, unudum" },
      { time: 70.65, text: "Cana düşər təlaş" },
      { time: 73.16, text: "O gecə nəsə baş verər" },
      { time: 75.32, text: "Məni anlayasan deyə" },
      { time: 112.48, text: "Ürək elə eşq istər" },
      { time: 115.94, text: "O gələcəyi oxşasın" },
      { time: 120.28, text: "Ölən, dirilən hisslər" },
      { time: 124.28, text: "Yeni həyata başlasın" },
      { time: 128.08, text: "Sözlərimi ruhunla" },
      { time: 130.76, text: "Nə də qəlbinlə" },
      { time: 132.72, text: "Duya bilmədin" },
      { time: 135.88, text: "Gözlərimə baxdıqca" },
      { time: 139.56, text: "Nələr hiss etdim, guya bilmədin" },
      { time: 144.88, text: "Kaş ürəyin ola daş" },
      { time: 148.08, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 152.62, text: "O gecə nəsə baş verər" },
      { time: 155.28, text: "Məni anlayasan deyə" },
      { time: 160.48, text: "Kaş səni daha yavaş" },
      { time: 164.04, text: "Unudum, unudum" },
      { time: 165.16, text: "Cana düşər təlaş" },
      { time: 168.32, text: "O gecə nəsə baş verər" },
      { time: 170.88, text: "Məni anlayasan deyə" },
      { time: 207.32, text: "Kaş ürəyin ola daş" },
      { time: 210.56, text: "Elə darıxasan, gözünə gələ yaş" },
      { time: 215.2, text: "O gecə nəsə baş verər" },
      { time: 217.72, text: "Məni anlayasan deyə" },
      { time: 222.92, text: "Kaş səni daha yavaş" },
      { time: 226.48, text: "Unudum, unudum" },
      { time: 228.3, text: "Cana düşər təlaş" },
      { time: 231.24, text: "O gecə nəsə baş verər" },
      { time: 233.36, text: "Məni anlayasan deyə" },
    ],
  },
  {
    title: "Yuxu",
    artist: "Nuri & Jane",
    duration: "3:33",
    durationSeconds: 213,
    fileName: "1772547560467.mp3",
    mood: "Yuxu · yaxınlıq",
    accent: "#8f7ad8",
    accentSoft: "#263456",
    src: "file:///C:/Users/ziyam/Desktop/1772547560467.mp3",
    portableSrc: "assets/music/05-yuxu.mp3",
    favoriteAt: 89.62,
    favoriteLine: "Ürək qədər yaxındasan",
    favoriteNote: "Məsafəni bir cümlə ilə yox edən hissə.",
    meaningTitle: "Uzaqda olsa da yuxuda və ürəkdə yaxın.",
    meaning:
      "Mahnı ayrılıqdan sonra belə bir insanın yuxuda, ruhda və gündəlik düşüncələrdə yanında qalmasını danışır.",
    lyrics: [
      { time: 31.86, text: "Küsdürməsin sözüm səni" },
      { time: 35.31, text: "Qədəh-qədəh süzüm səni" },
      { time: 39.12, text: "Unutmuşam özüm səni, yar" },
      { time: 45.88, text: "Mən indi öz yolumdayam" },
      { time: 49.28, text: "Ümidlərin yanındayam" },
      { time: 52.5, text: "Artıq yolun sonundayam, yar" },
      { time: 56.78, text: "Bu şəhərdə gələrikmi" },
      { time: 64.72, text: "Yenə üz-üzə?" },
      { time: 68.86, text: "Nə fərqi var uzaqdasan" },
      { time: 73.0, text: "Nə fərq edər yaxındasan" },
      { time: 76.36, text: "Hər gün şirin yuxumdasan" },
      { time: 79.56, text: "Yuxumdasan, yar" },
      { time: 83.84, text: "Ruhumdasan, yar" },
      { time: 85.7, text: "Elə bilmə uzaqdasan" },
      { time: 89.62, text: "Ürək qədər yaxındasan" },
      { time: 92.5, text: "Hər gün şirin röyamdasan" },
      { time: 96.3, text: "Canımdasan, yar" },
      { time: 99.66, text: "Yanımdasan, yar" },
      { time: 128.04, text: "Bu ayrılıq nədir ki sən" },
      { time: 131.3, text: "Gözündə çox böyütmüsən" },
      { time: 135.58, text: "Kimin sözün eşitmisən, yar?" },
      { time: 141.96, text: "Unutmağı unutmusan" },
      { time: 144.72, text: "Bu sevgini soyutmusan" },
      { time: 148.26, text: "Nə var geri qayıtmısan, yar?" },
      { time: 152.44, text: "Bu şəhərdə gələrikmi" },
      { time: 159.48, text: "Yenə üz-üzə?" },
      { time: 163.1, text: "Nə fərqi var uzaqdasan" },
      { time: 168.08, text: "Nə fərq edər yaxındasan" },
      { time: 170.8, text: "Hər gün şirin yuxumdasan" },
      { time: 174.22, text: "Yuxumdasan, yar" },
      { time: 178.4, text: "Ruhumdasan, yar" },
      { time: 180.42, text: "Elə bilmə uzaqdasan" },
      { time: 183.88, text: "Ürək qədər yaxındasan" },
      { time: 187.08, text: "Hər gün şirin röyamdasan" },
      { time: 190.32, text: "Canımdasan, yar" },
      { time: 194.62, text: "Yanımdasan, yar" },
    ],
  },
  {
    title: "Ты мой рай",
    artist: "NAYMADA feat. ANIVAR & Karen ТУЗ",
    duration: "4:00",
    durationSeconds: 240,
    fileName: "naymada.mp3",
    mood: "Sevgi · birlik",
    accent: "#b26ac7",
    accentSoft: "#42254f",
    portableSrc: "assets/music/06-naymada.mp3",
    favoriteAt: 24.2,
    favoriteLine: "Тебя люблю, за тобой лечу я слепо",
    favoriteNote: "Sevdiyin insanın ardınca tərəddüdsüz getmək hissi.",
    meaningTitle: "Birlikdə qurulan ev, yol və xəyallar.",
    meaning:
      "Mahnı incikliklərə baxmayaraq bir-birinə qayıdan, eyni evi və gələcəyi xəyal edən iki insanı danışır.",
    lyrics: [
      { time: 0.0, text: "Ты мой рай" },
      { time: 2.4, text: "Лечу я за тобой на край" },
      { time: 5.1, text: "Ты высоко со мной взлетай" },
      { time: 7.8, text: "Выше неба" },
      { time: 9.4, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 14.5, text: "Ты мой рай" },
      { time: 17.1, text: "Лечу я за тобой на край" },
      { time: 19.8, text: "Ты высоко со мной взлетай" },
      { time: 22.5, text: "Выше неба" },
      { time: 24.2, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 30.0, text: "Я хотел бы снять фильм про нас с тобой" },
      { time: 40.0, text: "Там, где любовь, с тобою в бой" },
      { time: 43.0, text: "Всё на реальных событиях" },
      { time: 46.0, text: "И ты в моих объятиях" },
      { time: 49.0, text: "Знай, я люблю тебя" },
      { time: 51.0, text: "Родная, ты знаешь меня" },
      { time: 54.0, text: "Я могу сорваться и обидеть" },
      { time: 58.0, text: "А потом обнять и всё исправить" },
      { time: 62.0, text: "Ты закрываешь на это глаза" },
      { time: 64.0, text: "По твоей щеке катится слеза" },
      { time: 66.0, text: "Нас тянет друг к другу, не держат тормоза" },
      { time: 69.0, text: "Просто прижмись ко мне, ведь ты моя муза" },
      { time: 73.0, text: "Видишь, мы мечтали, и сбылась наша мечта" },
      { time: 79.0, text: "Наш дом красим в цвета" },
      { time: 82.0, text: "Эмоции и грустная соната" },
      { time: 85.0, text: "По инерции летим в космос, как комета" },
      { time: 86.0, text: "Ты мой рай" },
      { time: 89.0, text: "Лечу я за тобой на край" },
      { time: 92.0, text: "Ты высоко со мной взлетай" },
      { time: 95.0, text: "Выше неба" },
      { time: 97.0, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 100.0, text: "Ты мой рай" },
      { time: 103.0, text: "Лечу я за тобой на край" },
      { time: 106.0, text: "Ты высоко со мной взлетай" },
      { time: 108.0, text: "Выше неба" },
      { time: 110.0, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 112.0, text: "Давай снимем кино" },
      { time: 114.0, text: "Хоть и много минорных нот и разлито вино" },
      { time: 117.0, text: "И свет от лампы так тускло освещает стены" },
      { time: 121.0, text: "Не важно где, важнее, с кем мы" },
      { time: 124.0, text: "Ведь ты была рядом" },
      { time: 126.0, text: "Когда падал, когда травили ядом" },
      { time: 129.0, text: "Я буду полным гадом, если от тебя отчалю" },
      { time: 132.0, text: "Иди ко мне, я дико по тебе скучаю" },
      { time: 136.0, text: "Поверь моим словам" },
      { time: 138.0, text: "С тобою рядом я сильный, но без тебя провал" },
      { time: 142.0, text: "Поверь моим глазам" },
      { time: 144.0, text: "Они расскажут тебе больше, чем я сказал" },
      { time: 148.0, text: "Так мило улыбалась" },
      { time: 151.0, text: "Когда без повода ты каждый день со мной ругалась" },
      { time: 154.0, text: "Мои мысли в тетрадь" },
      { time: 156.0, text: "Я не устану никогда о тебе писать" },
      { time: 160.0, text: "Ты мой рай" },
      { time: 163.0, text: "Лечу я за тобой на край" },
      { time: 166.0, text: "Ты высоко со мной взлетай" },
      { time: 169.0, text: "Выше неба" },
      { time: 171.0, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 179.0, text: "Ты мой рай" },
      { time: 182.0, text: "Лечу я за тобой на край" },
      { time: 185.0, text: "Ты высоко со мной взлетай" },
      { time: 188.0, text: "Выше неба" },
      { time: 190.0, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 198.0, text: "Ты мой рай" },
      { time: 201.0, text: "Лечу я за тобой на край" },
      { time: 204.0, text: "Ты высоко со мной взлетай" },
      { time: 207.0, text: "Выше неба" },
      { time: 209.0, text: "Тебя люблю, за тобой лечу я слепо" },
      { time: 217.0, text: "Ты мой рай" },
      { time: 220.0, text: "Лечу я за тобой на край" },
      { time: 223.0, text: "Ты высоко со мной взлетай" },
      { time: 226.0, text: "Выше неба" },
      { time: 228.0, text: "Тебя люблю, за тобой лечу я слепо" },
    ],
  },
  {
    title: "Heç Nədən",
    artist: "MC B.U.S x Masud Ramazanov",
    duration: "2:29",
    durationSeconds: 149,
    fileName: "mcmp3.mp3",
    mood: "Şəhər · düşüncə",
    accent: "#e08b55",
    accentSoft: "#513124",
    portableSrc: "assets/music/07-hec-neden.mp3",
    favoriteAt: 87.94,
    favoriteLine: "Sən mənə bir kitab, mən sənə bir vərəq",
    favoriteNote: "İki insanın eyni hekayədə fərqli ölçüdə qalmasını deyən misra.",
    meaningTitle: "Gedənin ardından boş qalan şəhər.",
    meaning:
      "Ayrılığın ağırlığını, cavabsız qalan qapıları və geri dönmək ümidi ilə yaşayan qəlbi danışır.",
    lyrics: [
      { time: 27.24, text: "Heç nədən getdi, gəlmədi" },
      { time: 29.52, text: "Qəlbimiz dərin bir qəbir" },
      { time: 31.8, text: "Üzərindədir güllərin" },
      { time: 34.04, text: "Bir sümüyəm, bir dəri" },
      { time: 36.28, text: "Heç nədən getdi, gəlmədi" },
      { time: 38.56, text: "Qəlbimiz dərin bir qəbir" },
      { time: 40.84, text: "Üzərindədir güllərin" },
      { time: 43.08, text: "Bir sümüyəm, bir dəri" },
      { time: 45.32, text: "Yollar aşıram" },
      { time: 47.32, text: "Sənə gələn yolda qalmışam" },
      { time: 49.32, text: "Yalanlara inanmışam" },
      { time: 52.0, text: "Yanmır burada işıqlar" },
      { time: 56.72, text: "Bir yol var: qapıları bağlı" },
      { time: 59.32, text: "Edən olmadı yardım" },
      { time: 61.92, text: "Arxasından baxdım" },
      { time: 64.22, text: "Qapılar arasında qaldım" },
      { time: 66.52, text: "Verilən hər bir qərar" },
      { time: 68.48, text: "Bilməlisən, o birindən betər" },
      { time: 70.44, text: "Gedirsənsə, get, onsuz da" },
      { time: 72.64, text: "Bir gün gələn bir gün gedər" },
      { time: 74.84, text: "Getdin tələm-tələsik" },
      { time: 76.66, text: "Qalmayıb da qram həvəsim" },
      { time: 78.48, text: "Üzərimdədir gözün və nəfsin" },
      { time: 81.0, text: "İstəmirəm, nə səs, nə nəfəsini" },
      { time: 83.52, text: "Ağır yük, ağır dərd, ağır bir boşluq" },
      { time: 85.73, text: "Sənsizliklə yaşayıram, məsum bir dostluq" },
      { time: 87.94, text: "Sən mənə bir kitab, mən sənə bir vərəq" },
      { time: 90.0, text: "Cırdın, atdın, getdin, eybi yoxdur, olsun" },
      { time: 92.0, text: "De, doğulmasınmı Günəş?" },
      { time: 94.0, text: "İndi açılmasınmı səhər?" },
      { time: 96.0, text: "Boğazımda bir qəhər" },
      { time: 98.0, text: "Artıq bomboş mənə bu şəhər" },
      { time: 100.0, text: "Gəl gör, şərtlər çox sərt, ağır bir dərd" },
      { time: 103.0, text: "Asılıb bədənimdən edir məni pərt" },
      { time: 106.0, text: "Göstər bir əl, dön geri gəl" },
      { time: 110.0, text: "Bitsin şübhə, dözmür bu qəlb" },
      { time: 120.24, text: "Heç nədən getdi, gəlmədi" },
      { time: 122.5, text: "Qəlbimiz dərin bir qəbir" },
      { time: 124.76, text: "Üzərindədir güllərin" },
      { time: 127.0, text: "Bir sümüyəm, bir dəri" },
      { time: 129.28, text: "Heç nədən getdi, gəlmədi" },
      { time: 131.54, text: "Qəlbimiz dərin bir qəbir" },
      { time: 133.8, text: "Üzərindədir güllərin" },
      { time: 136.06, text: "Bir sümüyəm, bir dəri" },
      { time: 138.52, text: "Yollar aşıram" },
      { time: 140.52, text: "Sənə gələn yolda qalmışam" },
      { time: 142.52, text: "Yalanlara inanmışam" },
      { time: 145.1, text: "Yanmır burada işıqlar" },
    ],
  },
];
